In [1]:
# 05-01. 원-핫 인코딩(One-hot encoding)

# 05-02. 소프트맥스 회귀(Softmax Regression) 이해하기 
# 로지스틱 회귀
# : 로지스틱 회귀에서 시그모이드 함수는 예측값을 0과 1사이의 값으로 만듭니다. 

# 소프트맥스 회귀
# : 소프트맥스 회귀는 확률의 총 합이 1이 되는 이 아이디어를 다중 클래스 분류 문제에 적용합니다 
# : H(x) = softmax(WX + B)

# 05-03. 소프트맥스 회귀의 비용 함수 구현하기 
import torch
import torch.nn.functional as F

torch.manual_seed(1)

# 1) 로우-레벨
z = torch.FloatTensor([1, 2, 3])

hypothesis = F.softmax(z, dim=0)
print(hypothesis)

print(hypothesis.sum())

# 임의의 3 x 5 행렬의 크기를 가진 텐서를 만든다. 
z = torch.rand(3, 5, requires_grad=True)

# 두 번째 차원에 대해서 소프트맥스 함수를 적용한다 
hypothesis = F.softmax(z, dim=1)
print(hypothesis)

# 소프트 맥스 함수의 출력값 = 예측값
# 3개의 샘플에 대해서 5개의 클래스 중 어떤 클래스가 정답인지를 예측 

tensor([0.0900, 0.2447, 0.6652])
tensor(1.)
tensor([[0.2645, 0.1639, 0.1855, 0.2585, 0.1277],
        [0.2430, 0.1624, 0.2322, 0.1930, 0.1694],
        [0.2226, 0.1986, 0.2326, 0.1594, 0.1868]], grad_fn=<SoftmaxBackward0>)


In [4]:
# 각 샘플에 대해서 임의의 레이블을 만든다. 
y = torch.randint(5, (3, )).long()
print(y)

# 각 레이블에 대해서 원-핫 인코딩을 수행 
# i) 모든 원소가 0의 값을 가진 3 x 5 텐서 생성 
y_one_hot = torch.zeros_like(hypothesis)
# ii) 
y_one_hot.scatter_(1, y.unsqueeze(1), 1)
print(y.unsqueeze(1))

# 원-핫 인코딩의 최종 결과
print(y_one_hot)

tensor([3, 1, 4])
tensor([[3],
        [1],
        [4]])
tensor([[0., 0., 0., 1., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 1.]])


In [5]:
# 비용함수 계산 
cost = (y_one_hot * -torch.log(hypothesis)).sum(dim=1).mean()
print(cost)

tensor(1.6160, grad_fn=<MeanBackward0>)


In [7]:
# 2) 하이-레벨
# Low level 
print(torch.log(F.softmax(z, dim=1)))

# High level 
print(F.log_softmax(z, dim=1))
print()

# Low level 
# 첫번째 수식
print((y_one_hot * -torch.log(F.softmax(z, dim=1))).sum(dim=1).mean())

# 두번째 수식
print((y_one_hot * -F.log_softmax(z, dim=1)).sum(dim=1).mean())

# High level 
# 세번째 수식
print(F.nll_loss(F.log_softmax(z, dim=1), y))

# nll(Negative Log Likelihood)

# 네번째 수식
print(F.cross_entropy(z, y))

tensor([[-1.3301, -1.8084, -1.6846, -1.3530, -2.0584],
        [-1.4147, -1.8174, -1.4602, -1.6450, -1.7758],
        [-1.5025, -1.6165, -1.4586, -1.8360, -1.6776]], grad_fn=<LogBackward0>)
tensor([[-1.3301, -1.8084, -1.6846, -1.3530, -2.0584],
        [-1.4147, -1.8174, -1.4602, -1.6450, -1.7758],
        [-1.5025, -1.6165, -1.4586, -1.8360, -1.6776]],
       grad_fn=<LogSoftmaxBackward0>)

tensor(1.6160, grad_fn=<MeanBackward0>)
tensor(1.6160, grad_fn=<MeanBackward0>)
tensor(1.6160, grad_fn=<NllLossBackward0>)
tensor(1.6160, grad_fn=<NllLossBackward0>)
